version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: tech-challenge-db
    ports:

  "5432:5432"
environment:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: tech_challenge
