version: '3.5'

services:
  db:
    image: postgres:latest
    container_name: tech-challenge-db
    environment:
      POSTGRES_DB: "tech-challenge-fase-3"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
