# Use root/example as user/password credentials
version: '3.1'

services:

  mongodb:
    image: mongo:latest
    container_name: tech-challenge-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: mockflix
    volumes:
      - tech-challenge-fase-04:/data/db
    ports:
      - "27017:27017"

volumes:
  tech-challenge-fase-04:
